# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'alex feldman'
email: 'felday@brandeis.edu'
description: 'Things I made, or things I wish I made.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://felday.info" # the base hostname & protocol for your site
github_username:  aalllxx

# Build settings
markdown: kramdown
